"""Outline generator — Step 1 of the V2 pipeline.

Generates a structured narrative outline via LLM (JSON mode).
Two-level fallback: JSON salvage → split-based outline construction.
"""

from __future__ import annotations

import json
import logging
from enum import Enum
from typing import Any, Callable, Awaitable

from pydantic import BaseModel, Field, field_validator

logger = logging.getLogger(__name__)


# ══════════════════════════════════════════════
#  SlideRole enum + synonyms
# ══════════════════════════════════════════════


class SlideRole(str, Enum):
    """Strict enum for narrative roles."""

    COVER = "cover"
    HOOK = "hook"
    CONTEXT = "context"
    PROBLEM = "problem"
    INSIGHT = "insight"
    PROOF = "proof"
    PROCESS = "process"
    PLAN = "plan"
    COMPARISON = "comparison"
    TEAM = "team"
    TAKEAWAY = "takeaway"
    CLOSING = "closing"


ROLE_SYNONYMS: dict[str, SlideRole] = {
    # context aliases
    "introduction": SlideRole.CONTEXT,
    "intro": SlideRole.CONTEXT,
    "background": SlideRole.CONTEXT,
    "overview": SlideRole.CONTEXT,
    "situation": SlideRole.CONTEXT,
    # hook aliases
    "opener": SlideRole.HOOK,
    "opening": SlideRole.HOOK,
    "accroche": SlideRole.HOOK,
    # proof aliases
    "data": SlideRole.PROOF,
    "results": SlideRole.PROOF,
    "kpi": SlideRole.PROOF,
    "metrics": SlideRole.PROOF,
    "evidence": SlideRole.PROOF,
    "chiffres": SlideRole.PROOF,
    "resultats": SlideRole.PROOF,
    # insight aliases
    "solution": SlideRole.INSIGHT,
    "approach": SlideRole.INSIGHT,
    "idea": SlideRole.INSIGHT,
    "proposition": SlideRole.INSIGHT,
    "value": SlideRole.INSIGHT,
    # process aliases
    "steps": SlideRole.PROCESS,
    "workflow": SlideRole.PROCESS,
    "method": SlideRole.PROCESS,
    "methodology": SlideRole.PROCESS,
    "etapes": SlideRole.PROCESS,
    # plan aliases
    "roadmap": SlideRole.PLAN,
    "next_steps": SlideRole.PLAN,
    "action": SlideRole.PLAN,
    "actions": SlideRole.PLAN,
    "planning": SlideRole.PLAN,
    # comparison aliases
    "versus": SlideRole.COMPARISON,
    "compare": SlideRole.COMPARISON,
    "pros_cons": SlideRole.COMPARISON,
    "benchmark": SlideRole.COMPARISON,
    "comparaison": SlideRole.COMPARISON,
    # takeaway aliases
    "summary": SlideRole.TAKEAWAY,
    "recap": SlideRole.TAKEAWAY,
    "key_points": SlideRole.TAKEAWAY,
    "resume": SlideRole.TAKEAWAY,
    "points_cles": SlideRole.TAKEAWAY,
    # closing aliases
    "cta": SlideRole.CLOSING,
    "contact": SlideRole.CLOSING,
    "thanks": SlideRole.CLOSING,
    "conclusion": SlideRole.CLOSING,
    "merci": SlideRole.CLOSING,
    "fin": SlideRole.CLOSING,
    # problem aliases
    "challenge": SlideRole.PROBLEM,
    "issue": SlideRole.PROBLEM,
    "pain": SlideRole.PROBLEM,
    "probleme": SlideRole.PROBLEM,
    "enjeu": SlideRole.PROBLEM,
    "defi": SlideRole.PROBLEM,
    # cover aliases
    "title": SlideRole.COVER,
    "titre": SlideRole.COVER,
    "couverture": SlideRole.COVER,
    # team aliases
    "equipe": SlideRole.TEAM,
    "members": SlideRole.TEAM,
    "profiles": SlideRole.TEAM,
}


def normalize_role(raw: str) -> SlideRole:
    """Normalize a raw LLM string to a SlideRole. Fallback: INSIGHT."""
    cleaned = raw.strip().lower().replace("-", "_").replace(" ", "_")
    try:
        return SlideRole(cleaned)
    except ValueError:
        return ROLE_SYNONYMS.get(cleaned, SlideRole.INSIGHT)


# ══════════════════════════════════════════════
#  Outline models
# ══════════════════════════════════════════════


class OutlineSlide(BaseModel):
    """One slide in the generated outline."""

    number: int
    role: SlideRole
    title: str
    goal: str = ""
    key_points: list[str] = Field(default_factory=list)

    @field_validator("role", mode="before")
    @classmethod
    def _normalize_role(cls, v: Any) -> SlideRole:
        if isinstance(v, str):
            return normalize_role(v)
        return v


class SuggestedTheme(BaseModel):
    """LLM-suggested theme for the presentation."""

    palette_name: str = ""
    primary: str = "#6C63FF"
    secondary: str = "#2D2B55"
    accent: str = "#FF6584"
    background: str = "#FFFFFF"
    text: str = "#333333"
    heading: str = "#1a1a2e"
    muted: str = "#6b7280"
    heading_font: str = "Inter"
    body_font: str = "Inter"


class GeneratedOutline(BaseModel):
    """Full outline generated by the LLM."""

    presentation_title: str
    audience: str = "general"
    tone: str = "professional"
    slides: list[OutlineSlide] = Field(default_factory=list)
    suggested_theme: SuggestedTheme | None = None


# ══════════════════════════════════════════════
#  Outline generation
# ══════════════════════════════════════════════

# Type alias for the LLM call function
LLMCallFn = Callable[[str, str], Awaitable[str]]


def _fix_outline(outline: GeneratedOutline, slide_count: int) -> GeneratedOutline:
    """Apply structural fix-ups to the outline."""
    slides = list(outline.slides)

    # Pad if too few slides
    while len(slides) < slide_count:
        n = len(slides) + 1
        slides.append(OutlineSlide(
            number=n,
            role=SlideRole.INSIGHT,
            title=f"Point {n}",
            goal="Additional context",
            key_points=[],
        ))

    # Trim if too many
    if len(slides) > slide_count:
        # Keep first and last, trim from middle
        keep_first = slides[0]
        keep_last = slides[-1]
        middle = slides[1:-1]
        needed = slide_count - 2
        trimmed = middle[:needed] if needed > 0 else []
        slides = [keep_first] + trimmed + [keep_last]

    # Force first slide to cover (AFTER padding/trimming)
    if slides and slides[0].role != SlideRole.COVER:
        slides[0] = slides[0].model_copy(update={"role": SlideRole.COVER})

    # Force last slide to takeaway or closing (AFTER padding/trimming)
    if slides and slides[-1].role not in (SlideRole.TAKEAWAY, SlideRole.CLOSING):
        slides[-1] = slides[-1].model_copy(update={"role": SlideRole.TAKEAWAY})

    # Re-number
    for i, s in enumerate(slides):
        if s.number != i + 1:
            slides[i] = s.model_copy(update={"number": i + 1})

    return outline.model_copy(update={"slides": slides})


def _salvage_json(raw_json: str, slide_count: int) -> GeneratedOutline | None:
    """Level 1 fallback: try to salvage a parseable but invalid JSON.

    Handles missing fields, wrong role names, etc.
    """
    try:
        data = json.loads(raw_json)
    except (json.JSONDecodeError, TypeError):
        return None

    if not isinstance(data, dict):
        return None

    # Try to find slides array
    slides_data = data.get("slides", [])
    if not isinstance(slides_data, list) or not slides_data:
        return None

    slides: list[OutlineSlide] = []
    for i, s in enumerate(slides_data):
        if not isinstance(s, dict):
            continue
        try:
            slide = OutlineSlide(
                number=s.get("number", i + 1),
                role=s.get("role", "insight"),
                title=s.get("title", f"Slide {i + 1}"),
                goal=s.get("goal", ""),
                key_points=s.get("key_points", []) if isinstance(s.get("key_points"), list) else [],
            )
            slides.append(slide)
        except Exception:
            # Even the validator failed — create minimal
            slides.append(OutlineSlide(
                number=i + 1,
                role=SlideRole.INSIGHT,
                title=s.get("title", f"Slide {i + 1}") if isinstance(s.get("title"), str) else f"Slide {i + 1}",
                goal="",
                key_points=[],
            ))

    if not slides:
        return None

    # Extract suggested theme if present
    suggested_theme = None
    theme_raw = data.get("suggested_theme")
    if isinstance(theme_raw, dict):
        try:
            suggested_theme = SuggestedTheme(**{
                k: v for k, v in theme_raw.items()
                if k in SuggestedTheme.model_fields
            })
        except Exception:
            suggested_theme = None

    outline = GeneratedOutline(
        presentation_title=data.get("presentation_title", data.get("title", "")),
        audience=data.get("audience", "general"),
        tone=data.get("tone", "professional"),
        slides=slides,
        suggested_theme=suggested_theme,
    )

    return _fix_outline(outline, slide_count)


def _build_outline_from_sections(
    sections: list[dict],
    slide_count: int,
    prompt: str,
) -> GeneratedOutline:
    """Level 2 fallback: build outline from split sections (existing pipeline).

    Takes sections from _split_prompt_into_sections() format:
    [{title, raw_text, role, split_method}, ...]
    """
    slides: list[OutlineSlide] = []
    for i, section in enumerate(sections):
        role_str = section.get("role", "insight")
        role = normalize_role(role_str)

        # Extract key points from raw_text
        raw = section.get("raw_text", "")
        key_points: list[str] = []
        if raw:
            # Try to extract bullet-like lines
            lines = [line.strip() for line in raw.split("\n") if line.strip()]
            for line in lines[:8]:
                cleaned = line.lstrip("- –—•*123456789.)·")
                if cleaned.strip() and len(cleaned.strip()) > 5:
                    key_points.append(cleaned.strip()[:300])

        slides.append(OutlineSlide(
            number=i + 1,
            role=role,
            title=section.get("title", f"Slide {i + 1}"),
            goal=raw[:600] if raw else "",
            key_points=key_points,
        ))

    # Extract title from first section or prompt
    pres_title = sections[0]["title"] if sections else prompt[:80]

    outline = GeneratedOutline(
        presentation_title=pres_title,
        slides=slides,
    )

    return _fix_outline(outline, slide_count)


async def generate_outline(
    *,
    prompt: str,
    slide_count: int,
    language: str,
    style: str,
    rag_context: str,
    llm_call: LLMCallFn,
    split_fallback: Callable | None = None,
) -> GeneratedOutline:
    """Generate a structured outline via LLM JSON mode.

    Args:
        prompt: User's presentation prompt
        slide_count: Requested number of slides
        language: e.g. "fr-FR"
        style: e.g. "professional"
        rag_context: RAG-retrieved context string
        llm_call: async callable(system_prompt, user_prompt) -> raw string
        split_fallback: optional callable(prompt, slide_count, language) -> sections
            Used as level 2 fallback if LLM fails completely

    Returns:
        GeneratedOutline with exactly slide_count slides
    """
    from app.services.presentation_prompts import OUTLINE_SYSTEM_PROMPT_V2

    system_prompt = OUTLINE_SYSTEM_PROMPT_V2.format(
        slide_count=slide_count,
        language=language,
        style=style,
        rag_context=rag_context or "Aucun contexte additionnel.",
    )
    user_prompt = prompt

    try:
        raw = await llm_call(system_prompt, user_prompt)

        # Strip markdown fences if present
        cleaned = raw.strip()
        if cleaned.startswith("```"):
            lines = cleaned.split("\n")
            # Remove first and last fence lines
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]
            cleaned = "\n".join(lines)

        try:
            outline = GeneratedOutline.model_validate_json(cleaned)
            outline = _fix_outline(outline, slide_count)
            logger.info(
                "Outline generated via LLM: %d slides (requested %d)",
                len(outline.slides), slide_count,
            )
            return outline
        except Exception as pydantic_err:
            logger.warning("Outline Pydantic validation failed: %s", pydantic_err)
            # Level 1 fallback: JSON salvage
            salvaged = _salvage_json(cleaned, slide_count)
            if salvaged:
                logger.info("Outline salvaged from partial JSON: %d slides", len(salvaged.slides))
                return salvaged
            logger.warning("JSON salvage failed, trying split fallback")

    except Exception as llm_err:
        logger.error("Outline LLM call failed: %s", llm_err)

    # Level 2 fallback: split-based outline
    if split_fallback:
        try:
            sections = await split_fallback(prompt, slide_count, language)
            outline = _build_outline_from_sections(sections, slide_count, prompt)
            logger.info("Outline built from split fallback: %d slides", len(outline.slides))
            return outline
        except Exception as split_err:
            logger.error("Split fallback also failed: %s", split_err)

    # Ultimate fallback: minimal outline
    logger.warning("All outline strategies failed, building minimal outline")
    slides = [
        OutlineSlide(number=1, role=SlideRole.COVER, title=prompt[:60], goal="Introduction", key_points=[]),
    ]
    for i in range(1, slide_count - 1):
        slides.append(OutlineSlide(
            number=i + 1, role=SlideRole.INSIGHT,
            title=f"Point {i}", goal="", key_points=[],
        ))
    slides.append(OutlineSlide(
        number=slide_count, role=SlideRole.TAKEAWAY,
        title="Points clés", goal="Résumé", key_points=[],
    ))
    return GeneratedOutline(presentation_title=prompt[:80], slides=slides)
